<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <form action = "/signup" method = "post">
        <input name = "first_name" placeholder="Имя">
        <input name = "last_name" placeholder="Фамилия">
        <input name = "email" placeholder="Email">
        <input name = "password" placeholder="Пароль" type="password">
        <input type = "submit" value = "sign up">
    </form>

</div>
</body>
</html>